[package]
name = "folivafy"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "entity", "migration"]

[dependencies]
anyhow = "1.0.70"
axum = "0.6.16"
axum-macros = "0.3.7"
dotenvy = "0.15.7"
entity = { path = "entity" }
garde = "0.11.2"
jwt-authorizer = { git = "https://github.com/cduvray/jwt-authorizer", rev = "7fc800d", default-features = false, features = [
"rustls-tls",
] }
#jwt-authorizer = "0.9.0"
migration = { path = "migration" } # depends on your needs
openapi = { path = "./generated", default-features = false, features = [
    "lazy_static",
    "regex",
] }
regex = "1"
reqwest = { version = "0.11.16", default-features = false, features = ["rustls", "rustls-tls"] }
sea-orm = { version = "0", features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-postgres",
] }
sea-query = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = "0.6.3"
thiserror = "1.0.40"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
validator = { version = "0.16.0", features = ["derive"] }
