[package]
name = "folivafy"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "entity", "migration"]

[dependencies]
anyhow = "1.0"
axum = "0.6"
axum-macros = "0.3.7"
dotenvy = "0.15.7"
entity = { path = "entity" }
jwt-authorizer = { git = "https://github.com/cduvray/jwt-authorizer", rev = "7fc800d", default-features = false, features = [
"rustls-tls",
] }
#jwt-authorizer = "0.9.0"
lazy_static = "1.4"
migration = { path = "migration" } # depends on your needs
openapi = { path = "./generated", default-features = false, features = [
    "lazy_static",
    "regex",
] }
regex = "1"
reqwest = { version = "0.11", default-features = false, features = ["rustls", "rustls-tls"] }
sea-orm = { version = "0", features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-postgres",
] }
sea-query = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.6", features = [ "postgres", "runtime-tokio-rustls" ] }
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tower-http = { version = "0.4", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = {version = "1", features = ["serde", "v4"]}
validator = { version = "0.16.0", features = ["derive"] }
