name: folivafy_devcontainer

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: "service:db"
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:17.2
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - "8101:8101"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    depends_on:
      - db
    command:
      - start-dev
      - --import-realm
    # Use the network stack of another container, specified via its name
    # https://docs.docker.com/engine/reference/run/#network-settings
    network_mode: "service:db"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8101
      - KC_DB=postgres
      - KC_DB_PASSWORD=zhTCZbEAd8uQn0g
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_URL_HOST=db
      - KC_DB_USERNAME=keycloakuser
    volumes:
      - ../dev_realm.json:/opt/keycloak/data/import/dev_realm.json

  maildev:
    image: maildev/maildev
    network_mode: "service:db"
