//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::collection::Entity as Collection;
pub use super::collection_document::Entity as CollectionDocument;
pub use super::event::Entity as Event;
pub use super::grant::Entity as Grant;
