//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::collection::Entity as Collection;
pub use super::collection_document::Entity as CollectionDocument;
pub use super::event::Entity as Event;
