//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::collection::Entity as Collection;
pub use super::collection_document::Entity as CollectionDocument;
pub use super::event::Entity as Event;
pub use super::grant::Entity as Grant;
